/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Auth:Token
         * @description Authenticate with email and password.
         */
        post: operations["auth_token_api_auth_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Auth:Refresh
         * @description Use a valid refresh token to get a new access token.
         */
        post: operations["auth_refresh_api_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/request-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Auth:Request-Reset
         * @description Request a password reset email.
         *
         *     Always returns success to prevent email enumeration.
         */
        post: operations["auth_request_reset_api_auth_request_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Auth:Reset-Password
         * @description Reset password with valid token.
         */
        post: operations["auth_reset_password_api_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile:Get */
        get: operations["profile_get_api_profile_get"];
        /**
         * Profile:Update
         * @description Update user profile, allowing phone and address changes but blocking other fields for active investments.
         */
        put: operations["profile_update_api_profile_put"];
        /**
         * Profile:Register
         * @description Create a new user account with email and password.
         */
        post: operations["profile_register_api_profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Profile:Patch
         * @description Patch user profile, blocking account type changes for active investments.
         */
        patch: operations["profile_patch_api_profile_patch"];
        trace?: never;
    };
    "/api/profile/confirm/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Profile:Confirm
         * @description Verify email with token and auto-login user.
         */
        put: operations["profile_confirm_api_profile_confirm__user_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/change_password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Profile:Change Password */
        put: operations["profile_change_password_api_profile_change_password_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Investments:List */
        get: operations["investments_list_api_investments_get"];
        put?: never;
        /** Investments:Create */
        post: operations["investments_create_api_investments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investments/attestations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Investments:List-Attestations */
        get: operations["investments_list_attestations_api_investments_attestations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investments/{investment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Investments:Get */
        get: operations["investments_get_api_investments__investment_id__get"];
        put?: never;
        post?: never;
        /** Investments:Delete */
        delete: operations["investments_delete_api_investments__investment_id__delete"];
        options?: never;
        head?: never;
        /** Investments:Update */
        patch: operations["investments_update_api_investments__investment_id__patch"];
        trace?: never;
    };
    "/api/investments/{investment_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Investments:Submit */
        post: operations["investments_submit_api_investments__investment_id__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investments/{investment_id}/calculation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Investments:Calculation */
        get: operations["investments_calculation_api_investments__investment_id__calculation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investments/{investment_id}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Investments:Withdraw */
        post: operations["investments_withdraw_api_investments__investment_id__withdraw_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investments/{investment_id}/agreement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Investments:Get-Agreement
         * @description Retrieve the investment agreement PDF document.
         *
         *     For investments in draft status, the PDF will be generated on the fly using the bond document
         *     template. For investments that have been submitted or processed, the saved PDF will be loaded
         *     from storage if it exists.
         */
        get: operations["investments_get_agreement_api_investments__investment_id__agreement_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investments/{investment_id}/attestations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Investments:Create-Attestation */
        post: operations["investments_create_attestation_api_investments__investment_id__attestations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/withdrawals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Withdrawals:List */
        get: operations["withdrawals_list_api_withdrawals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/withdrawals/{withdrawal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Withdrawals:Get */
        get: operations["withdrawals_get_api_withdrawals__withdrawal_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activity/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Activity:List User Activity */
        get: operations["activity_list_user_activity_api_activity_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin:Users:List */
        get: operations["admin_users_list_api_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Admin:Users:Delete */
        delete: operations["admin_users_delete_api_admin_users__user_id__delete"];
        options?: never;
        head?: never;
        /** Admin:Users:Update */
        patch: operations["admin_users_update_api_admin_users__user_id__patch"];
        trace?: never;
    };
    "/api/admin/activity/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin:Activity:List Events */
        get: operations["admin_activity_list_events_api_admin_activity_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/investments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin:Investments:List */
        get: operations["admin_investments_list_api_admin_investments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/investments/{investment_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin:Investments:Approve */
        post: operations["admin_investments_approve_api_admin_investments__investment_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/investments/{investment_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin:Investments:Reject */
        post: operations["admin_investments_reject_api_admin_investments__investment_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/transactions/migrate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin:Transactions:Migrate */
        post: operations["admin_transactions_migrate_api_admin_transactions_migrate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/withdrawals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin:Withdrawals:List */
        get: operations["admin_withdrawals_list_api_admin_withdrawals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/withdrawals/{withdrawal_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin:Withdrawals:Approve */
        post: operations["admin_withdrawals_approve_api_admin_withdrawals__withdrawal_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/time-machine/set": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin:Time-Machine:Set */
        post: operations["admin_time_machine_set_api_admin_time_machine_set_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/time-machine/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin:Time-Machine:Reset */
        post: operations["admin_time_machine_reset_api_admin_time_machine_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/time-machine/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin:Time-Machine:Status */
        get: operations["admin_time_machine_status_api_admin_time_machine_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plaid/link-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Plaid:Create-Link-Token */
        post: operations["plaid_create_link_token_api_plaid_link_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health:Check
         * @description Return service health, reporting database connectivity state.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccountType
         * @enum {string}
         */
        AccountType: "individual" | "joint" | "entity" | "ira";
        /** AccreditationAttestationCreateRequest */
        AccreditationAttestationCreateRequest: {
            status: components["schemas"]["AccreditationStatus"];
            accreditedType?: components["schemas"]["AccreditedType"] | null;
            /** Tenpercentlimitconfirmed */
            tenPercentLimitConfirmed?: boolean | null;
        };
        /** AccreditationAttestationDetailResponse */
        AccreditationAttestationDetailResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            attestation: components["schemas"]["AccreditationAttestationResponse"];
        };
        /** AccreditationAttestationResponse */
        AccreditationAttestationResponse: {
            /** Id */
            id: number;
            /** Userid */
            userId: string;
            /** Investmentid */
            investmentId: string;
            status: components["schemas"]["AccreditationStatus"];
            accreditedType: components["schemas"]["AccreditedType"] | null;
            /** Tenpercentlimitconfirmed */
            tenPercentLimitConfirmed: boolean;
            /** Attestedat */
            attestedAt: string;
        };
        /**
         * AccreditationStatus
         * @enum {string}
         */
        AccreditationStatus: "accredited" | "not_accredited";
        /**
         * AccreditedType
         * @enum {string}
         */
        AccreditedType: "assets" | "income";
        /** AccrualSegmentResponse */
        AccrualSegmentResponse: {
            /** Segmenttype */
            segmentType: string;
            /** Startdate */
            startDate: string;
            /** Enddate */
            endDate: string;
            /** Daysinsegment */
            daysInSegment: number;
            /** Startingbalance */
            startingBalance: string;
            /** Endingbalance */
            endingBalance: string;
            /** Earningsinsegment */
            earningsInSegment: string;
        };
        /** ActivityEventResponse */
        ActivityEventResponse: {
            /** Id */
            id: string;
            /** Userid */
            userId: number;
            /** Investmentid */
            investmentId?: number | null;
            /** Activitytype */
            activityType: string;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Eventmetadata */
            eventMetadata?: string | null;
            /** Eventdate */
            eventDate: string;
            /** Createdat */
            createdAt: string;
        };
        /** AddressDetail */
        AddressDetail: {
            /** Street1 */
            street1: string;
            /** Street2 */
            street2?: string | null;
            /** City */
            city: string;
            /** State */
            state: string;
            /** Zip */
            zip: string;
        };
        /** AddressUpdateRequest */
        AddressUpdateRequest: {
            /** Street1 */
            street1?: string | null;
            /** Street2 */
            street2?: string | null;
            /** City */
            city?: string | null;
            /** State */
            state?: string | null;
            /** Zip */
            zip?: string | null;
        };
        /** AdminUserUpdateRequest */
        AdminUserUpdateRequest: {
            /** Firstname */
            firstName?: string | null;
            /** Lastname */
            lastName?: string | null;
            /** Email */
            email?: string | null;
            /** Ssn */
            ssn?: string | null;
        };
        /** AppTimeResponse */
        AppTimeResponse: {
            /** Apptime */
            appTime: string;
        };
        /** AuthorizedRepresentativeDetail */
        AuthorizedRepresentativeDetail: {
            /** Firstname */
            firstName: string;
            /** Lastname */
            lastName: string;
            /** Dob */
            dob: string | null;
            /** Ssn */
            ssn: string;
            address: components["schemas"]["AddressDetail"] | null;
        };
        /** AuthorizedRepresentativeUpdateRequest */
        AuthorizedRepresentativeUpdateRequest: {
            /** Firstname */
            firstName: string;
            /** Lastname */
            lastName: string;
            /**
             * Dob
             * Format: date
             */
            dob: string;
            /** Ssn */
            ssn: string;
            address: components["schemas"]["AddressDetail"];
        };
        /** CalculationDetails */
        CalculationDetails: {
            /** Totalperiods */
            totalPeriods: number;
            /** Monthselapsed */
            monthsElapsed: string;
            /** Accrualsegments */
            accrualSegments: components["schemas"]["AccrualSegmentResponse"][];
        };
        /** ChangePasswordRequest */
        ChangePasswordRequest: {
            /**
             * Currentpassword
             * @description Current password
             */
            currentPassword: string;
            /**
             * Newpassword
             * @description New password
             */
            newPassword: string;
        };
        /** ChangePasswordResponse */
        ChangePasswordResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            user: components["schemas"]["UserResponse"];
        };
        /** ComplianceInfo */
        ComplianceInfo: {
            status: components["schemas"]["AccreditationStatus"];
            accreditedType: components["schemas"]["AccreditedType"] | null;
            /** Tenpercentlimitconfirmed */
            tenPercentLimitConfirmed: boolean | null;
            /** Attestedat */
            attestedAt: string;
        };
        /** ConfirmAccountRequest */
        ConfirmAccountRequest: {
            /**
             * Verificationcode
             * @description Email verification code
             */
            verificationCode: string;
        };
        /** ConfirmAccountResponse */
        ConfirmAccountResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            user: components["schemas"]["UserResponse"];
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Auto Logged In
             * @default true
             */
            auto_logged_in: boolean;
        };
        /** EntityDetail */
        EntityDetail: {
            /** Name */
            name: string;
            /** Registrationdate */
            registrationDate: string | null;
            /** Taxid */
            taxId: string;
            /** Phone */
            phone?: string | null;
            address?: components["schemas"]["AddressDetail"] | null;
        };
        /** EntityUpdateRequest */
        EntityUpdateRequest: {
            /** Name */
            name: string;
            /**
             * Registrationdate
             * Format: date
             */
            registrationDate: string;
            /** Taxid */
            taxId: string;
            /** Phone */
            phone?: string | null;
            address?: components["schemas"]["AddressDetail"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InvestmentCalculationData */
        InvestmentCalculationData: {
            /** Investmentid */
            investmentId: number;
            /** Principalamount */
            principalAmount: string;
            /** Currentvalue */
            currentValue: string;
            /** Totalearnings */
            totalEarnings: string;
            /** Apyrate */
            apyRate: string;
            lockupPeriod: components["schemas"]["LockupPeriod"];
            paymentFrequency: components["schemas"]["PaymentFrequency"];
            /** Confirmedat */
            confirmedAt?: string | null;
            /** Lockupendat */
            lockupEndAt?: string | null;
            /** Asofdate */
            asOfDate: string | null;
            /** Iswithdrawable */
            isWithdrawable: boolean;
            /** Daysuntilwithdrawable */
            daysUntilWithdrawable?: number | null;
            details: components["schemas"]["CalculationDetails"];
        };
        /** InvestmentCalculationResponse */
        InvestmentCalculationResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            data: components["schemas"]["InvestmentCalculationData"];
        };
        /** InvestmentCreateRequest */
        InvestmentCreateRequest: {
            /** Amount */
            amount: number | string;
            /** @description Supported values: ('1-year', '3-year') */
            lockupPeriod: components["schemas"]["LockupPeriod"];
            /** @description Supported values: ('monthly', 'compounding') */
            paymentFrequency: components["schemas"]["PaymentFrequency"];
            /** @description Supported values: ('ach', 'wire') */
            paymentMethod: components["schemas"]["PaymentMethod"];
        };
        /** InvestmentDetailResponse */
        InvestmentDetailResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            investment: components["schemas"]["InvestmentResponse"];
        };
        /** InvestmentListResponse */
        InvestmentListResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Investments */
            investments: components["schemas"]["InvestmentResponse"][];
        };
        /** InvestmentResponse */
        InvestmentResponse: {
            /** Id */
            id: number;
            /** Userid */
            userId: number;
            /** Amount */
            amount: string;
            /** Bonds */
            bonds: number;
            status: components["schemas"]["InvestmentStatus"];
            lockupPeriod: components["schemas"]["LockupPeriod"];
            paymentFrequency: components["schemas"]["PaymentFrequency"];
            paymentMethod: components["schemas"]["PaymentMethod"];
            /** Autoapproved */
            autoApproved: boolean;
            /** Requiresmanualapproval */
            requiresManualApproval: boolean;
            /** Confirmedat */
            confirmedAt?: string | null;
            /** Lockupendat */
            lockupEndAt?: string | null;
            /** Createdat */
            createdAt: string | null;
            /** Updatedat */
            updatedAt: string | null;
            compliance?: components["schemas"]["ComplianceInfo"] | null;
        };
        /**
         * InvestmentStatus
         * @enum {string}
         */
        InvestmentStatus: "draft" | "pending" | "active" | "withdrawal_notice" | "withdrawn" | "rejected";
        /** InvestmentUpdateRequest */
        InvestmentUpdateRequest: {
            /** Amount */
            amount?: number | string | null;
            /** @description Supported values: ('1-year', '3-year') */
            lockupPeriod?: components["schemas"]["LockupPeriod"] | null;
            /** @description Supported values: ('monthly', 'compounding') */
            paymentFrequency?: components["schemas"]["PaymentFrequency"] | null;
            /** @description Supported values: ('ach', 'wire') */
            paymentMethod?: components["schemas"]["PaymentMethod"] | null;
        };
        /** JointHolderDetail */
        JointHolderDetail: {
            /** Firstname */
            firstName: string;
            /** Lastname */
            lastName: string;
            /** Email */
            email: string;
            /** Phone */
            phone: string;
            /** Dob */
            dob: string | null;
            /** Ssn */
            ssn: string;
            address: components["schemas"]["AddressDetail"] | null;
        };
        /** JointHolderUpdateRequest */
        JointHolderUpdateRequest: {
            /** Firstname */
            firstName: string;
            /** Lastname */
            lastName: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Phone */
            phone: string;
            /**
             * Dob
             * Format: date
             */
            dob: string;
            /** Ssn */
            ssn: string;
            address: components["schemas"]["AddressDetail"];
        };
        /** LinkTokenResponse */
        LinkTokenResponse: {
            /** Link Token */
            link_token: string;
            /** Expiration */
            expiration: string;
        };
        /**
         * LockupPeriod
         * @enum {string}
         */
        LockupPeriod: "1-year" | "3-year";
        /** Page[AccreditationAttestationResponse] */
        Page_AccreditationAttestationResponse_: {
            /** Items */
            items: components["schemas"]["AccreditationAttestationResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** Page[ActivityEventResponse] */
        Page_ActivityEventResponse_: {
            /** Items */
            items: components["schemas"]["ActivityEventResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** Page[InvestmentResponse] */
        Page_InvestmentResponse_: {
            /** Items */
            items: components["schemas"]["InvestmentResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** Page[UserDetail] */
        Page_UserDetail_: {
            /** Items */
            items: components["schemas"]["UserDetail"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** Page[WithdrawalResponse] */
        Page_WithdrawalResponse_: {
            /** Items */
            items: components["schemas"]["WithdrawalResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** PasswordResetConfirm */
        PasswordResetConfirm: {
            /**
             * Token
             * @description Password reset token
             */
            token: string;
            /**
             * New Password
             * @description New password
             */
            new_password: string;
        };
        /** PasswordResetRequest */
        PasswordResetRequest: {
            /**
             * Email
             * Format: email
             * @description Email address for reset
             */
            email: string;
        };
        /** PasswordResetResponse */
        PasswordResetResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
        };
        /**
         * PaymentFrequency
         * @enum {string}
         */
        PaymentFrequency: "monthly" | "compounding";
        /**
         * PaymentMethod
         * @enum {string}
         */
        PaymentMethod: "ach" | "wire";
        /** ProfilePatchRequest */
        ProfilePatchRequest: {
            /** Phone */
            phone?: string | null;
            address?: components["schemas"]["AddressUpdateRequest"] | null;
            accountType?: components["schemas"]["AccountType"] | null;
        };
        /** ProfilePatchResponse */
        ProfilePatchResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            user: components["schemas"]["UserDetail"];
        };
        /** ProfileUpdateRequest */
        ProfileUpdateRequest: {
            /** Firstname */
            firstName?: string | null;
            /** Lastname */
            lastName?: string | null;
            /** Phone */
            phone?: string | null;
            /** Dob */
            dob?: string | null;
            /** Ssn */
            ssn?: string | null;
            address?: components["schemas"]["AddressUpdateRequest"] | null;
            accountType?: components["schemas"]["AccountType"] | null;
            /** Jointholdingtype */
            jointHoldingType?: string | null;
            jointHolder?: components["schemas"]["JointHolderUpdateRequest"] | null;
            entity?: components["schemas"]["EntityUpdateRequest"] | null;
            authorizedRepresentative?: components["schemas"]["AuthorizedRepresentativeUpdateRequest"] | null;
        };
        /** ProfileUpdateResponse */
        ProfileUpdateResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            user: components["schemas"]["UserDetail"];
        };
        /** RefreshTokenRequest */
        RefreshTokenRequest: {
            /**
             * Refresh Token
             * @description JWT refresh token
             */
            refresh_token: string;
        };
        /** RefreshTokenResponse */
        RefreshTokenResponse: {
            /**
             * Access Token
             * @description New JWT access token
             */
            access_token: string;
            /**
             * Token Type
             * @description Token type
             * @default bearer
             */
            token_type: string;
            /**
             * Expires In
             * @description Access token expiration time in seconds
             */
            expires_in: number;
        };
        /** ResetAppTimeResponse */
        ResetAppTimeResponse: {
            /** Apptime */
            appTime: string;
            /** Message */
            message: string;
        };
        /** SetAppTimeRequest */
        SetAppTimeRequest: {
            /** Apptime */
            appTime: string;
        };
        /** TimeMachineStatusResponse */
        TimeMachineStatusResponse: {
            /** Apptime */
            appTime: string;
            /** Isoverridden */
            isOverridden: boolean;
            /** Systemtime */
            systemTime: string;
            /** Offsetseconds */
            offsetSeconds: number;
            /** Offsetdisplay */
            offsetDisplay: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /**
             * Access Token
             * @description JWT access token
             */
            access_token: string;
            /**
             * Refresh Token
             * @description JWT refresh token
             */
            refresh_token: string;
            /**
             * Token Type
             * @description Token type
             * @default bearer
             */
            token_type: string;
            /**
             * Expires In
             * @description Access token expiration time in seconds
             */
            expires_in: number;
        };
        /** TransactionMigrateResponse */
        TransactionMigrateResponse: {
            /** Transactionsdeleted */
            transactionsDeleted: number;
            /** Eventsdeleted */
            eventsDeleted: number;
            /** Transactionscreated */
            transactionsCreated: number;
        };
        /** UserDetail */
        UserDetail: {
            /**
             * Id
             * @description User ID (can be numeric or human-readable like USR-1001)
             */
            id: string;
            /** Email */
            email: string;
            /** Isverified */
            isVerified: boolean;
            /** Verifiedat */
            verifiedAt?: string | null;
            /**
             * Isadmin
             * @default false
             */
            isAdmin: boolean;
            /** Firstname */
            firstName?: string | null;
            /** Lastname */
            lastName?: string | null;
            /** Phone */
            phone?: string | null;
            /** Dob */
            dob?: string | null;
            /** Ssn */
            ssn?: string | null;
            address?: components["schemas"]["AddressDetail"] | null;
            accountType?: string | null;
            /** Jointholdingtype */
            jointHoldingType?: string | null;
            jointHolder?: components["schemas"]["JointHolderDetail"] | null;
            entity?: components["schemas"]["EntityDetail"] | null;
            authorizedRepresentative?: components["schemas"]["AuthorizedRepresentativeDetail"] | null;
            /** Createdat */
            createdAt?: string | null;
            /** Updatedat */
            updatedAt?: string | null;
            /** Lastactiveat */
            lastActiveAt?: string | null;
            /** Sessionexpiresat */
            sessionExpiresAt?: string | null;
        };
        /** UserDetailResponse */
        UserDetailResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            user: components["schemas"]["UserDetail"];
        };
        /** UserRegisterRequest */
        UserRegisterRequest: {
            /**
             * Email
             * Format: email
             * @description User's email address
             */
            email: string;
            /**
             * Password
             * @description User's password
             */
            password: string;
        };
        /** UserRegisterResponse */
        UserRegisterResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            user: components["schemas"]["UserResponse"];
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Is Verified */
            is_verified: boolean;
            /** Created At */
            created_at: string | null;
            /** Updated At */
            updated_at: string | null;
            /** Last Active At */
            last_active_at?: string | null;
            /** Session Expires At */
            session_expires_at?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WithdrawalDetailResponse */
        WithdrawalDetailResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            withdrawal: components["schemas"]["WithdrawalResponse"];
        };
        /** WithdrawalListResponse */
        WithdrawalListResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Withdrawals */
            withdrawals: components["schemas"]["WithdrawalResponse"][];
        };
        /** WithdrawalResponse */
        WithdrawalResponse: {
            /** Id */
            id: number;
            /** Userid */
            userId: number;
            /** Investmentid */
            investmentId: number;
            /** Amount */
            amount: string;
            /** Principalamount */
            principalAmount: string;
            /** Earningsamount */
            earningsAmount: string;
            status: components["schemas"]["WithdrawalStatus"];
            withdrawalType: components["schemas"]["WithdrawalType"];
            /** Adminterminated */
            adminTerminated: boolean;
            /** Adminuserid */
            adminUserId?: number | null;
            /** Lockupoverridden */
            lockupOverridden: boolean;
            /** Investmentsnapshot */
            investmentSnapshot?: {
                [key: string]: unknown;
            } | null;
            /** Requestedat */
            requestedAt: string | null;
            /** Approvedat */
            approvedAt?: string | null;
            /** Rejectedat */
            rejectedAt?: string | null;
            /** Paidat */
            paidAt?: string | null;
            /** Payoutcalculatedat */
            payoutCalculatedAt?: string | null;
            /** Rejectionreason */
            rejectionReason?: string | null;
            /** Adminnotes */
            adminNotes?: string | null;
            /** Createdat */
            createdAt: string | null;
            /** Updatedat */
            updatedAt: string | null;
        };
        /**
         * WithdrawalStatus
         * @enum {string}
         */
        WithdrawalStatus: "pending" | "approved" | "rejected" | "paid" | "cancelled";
        /**
         * WithdrawalType
         * @enum {string}
         */
        WithdrawalType: "normal" | "admin_terminated";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_token_api_auth_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Email
                     * Format: email
                     * @description User's email address
                     */
                    email: string;
                    /**
                     * Password
                     * @description User's password
                     */
                    password: string;
                };
                "application/x-www-form-urlencoded": {
                    /** Format: email */
                    username: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    auth_refresh_api_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_request_reset_api_auth_request_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordResetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_reset_password_api_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirm"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordResetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profile_get_api_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetailResponse"];
                };
            };
        };
    };
    profile_update_api_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileUpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profile_register_api_profile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRegisterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profile_patch_api_profile_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfilePatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfilePatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profile_confirm_api_profile_confirm__user_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmAccountRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfirmAccountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profile_change_password_api_profile_change_password_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangePasswordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    investments_list_api_investments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestmentListResponse"];
                };
            };
        };
    };
    investments_create_api_investments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestmentCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestmentDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    investments_list_attestations_api_investments_attestations_get: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Page size */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AccreditationAttestationResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    investments_get_api_investments__investment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestmentDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    investments_delete_api_investments__investment_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    investments_update_api_investments__investment_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestmentUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestmentDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    investments_submit_api_investments__investment_id__submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestmentDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    investments_calculation_api_investments__investment_id__calculation_get: {
        parameters: {
            query?: {
                asOfDate?: string | null;
            };
            header?: never;
            path: {
                investment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestmentCalculationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    investments_withdraw_api_investments__investment_id__withdraw_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WithdrawalDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    investments_get_agreement_api_investments__investment_id__agreement_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    investments_create_attestation_api_investments__investment_id__attestations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccreditationAttestationCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccreditationAttestationDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    withdrawals_list_api_withdrawals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WithdrawalListResponse"];
                };
            };
        };
    };
    withdrawals_get_api_withdrawals__withdrawal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                withdrawal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WithdrawalDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activity_list_user_activity_api_activity_events_get: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Page size */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ActivityEventResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_users_list_api_admin_users_get: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Page size */
                size?: number;
                is_verified?: boolean | null;
                account_type?: string | null;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_UserDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_users_delete_api_admin_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_users_update_api_admin_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUserUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_activity_list_events_api_admin_activity_events_get: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Page size */
                size?: number;
                user_id?: number | null;
                investment_id?: number | null;
                activity_type?: string | null;
                status?: string | null;
                search?: string | null;
                order_by?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ActivityEventResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_investments_list_api_admin_investments_get: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Page size */
                size?: number;
                status?: string | null;
                user_id?: number | null;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_InvestmentResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_investments_approve_api_admin_investments__investment_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_investments_reject_api_admin_investments__investment_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_transactions_migrate_api_admin_transactions_migrate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionMigrateResponse"];
                };
            };
        };
    };
    admin_withdrawals_list_api_admin_withdrawals_get: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Page size */
                size?: number;
                status?: string | null;
                user_id?: number | null;
                investment_id?: number | null;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_WithdrawalResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_withdrawals_approve_api_admin_withdrawals__withdrawal_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                withdrawal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WithdrawalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_time_machine_set_api_admin_time_machine_set_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetAppTimeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppTimeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_time_machine_reset_api_admin_time_machine_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetAppTimeResponse"];
                };
            };
        };
    };
    admin_time_machine_status_api_admin_time_machine_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeMachineStatusResponse"];
                };
            };
        };
    };
    plaid_create_link_token_api_plaid_link_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkTokenResponse"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
