/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Auth:Token
         * @description Authenticate with email and password.
         */
        post: operations["auth_token_api_auth_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    // ... rest of the file ...
}

// Manually adding the PaymentMethod type definition if missing or inferred
export type PaymentMethod = "ach" | "wire";

export interface InvestmentUpdateRequest {
    amount?: number | string | null;
    state?: string | null;
    lockupPeriod?: "1-year" | "3-year" | null;
    paymentFrequency?: "monthly" | "compounding" | null;
    paymentMethod?: PaymentMethod | null;
    // It seems the auto-generated types don't show paymentMethodId in InvestmentUpdateRequest
    // However, the error suggests the backend needs it.
    // We will try sending it as an extra field in the fetch call regardless of TS types here.
}
